name: Build and Test

env:
  VERSION: 3.3.2

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: Build Snap
    runs-on: ubuntu-latest
    outputs:
      snap-file: ${{ steps.snapcraft.outputs.snap }}
    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v3
        run: |
          ls -la snap/local/

      - id: dependencies 
        name: Upgrade linux deps
        run: |
          sudo apt-get update
          sudo apt-get upgrade --yes

      - id: snapcraft
        name: Build snap
        uses: snapcore/action-build@v1

      - id: upload
        name: Upload built snap job artifact
        uses: actions/upload-artifact@v3
        with:
          name: charmed-kafka_snap_amd64
          path: charmed-kafka_${{env.VERSION}}_amd64.snap

  test:
    name: Test Snap
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download snap file
        uses: actions/download-artifact@v3
        with:
          name: charmed-kafka_snap_amd64
          path: .

      - name: Install snap file
        run: |
          sudo snap install charmed-kafka_${{env.VERSION}}_amd64.snap --dangerous

      - name: Start Charmed-Kafka
        run: |
          sudo snap start charmed-kafka
          sleep 10

      - name: Check topic creation
        run: |
          topic_creation=$(charmed-kafka.topics --create --topic test --bootstrap-server localhost:9092)
          if [ "$topic_creation" != "Created topic test." ]; then
              exit 1
          fi
